version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./pets/public:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./import.sql:/docker-entrypoint-initdb.d/0_init.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: pets
      MYSQL_USER: admin1
      MYSQL_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db